services:
  zookeeper:
    image: bitnamilegacy/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'

  kafka:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka_data:/bitnami/kafka'
    depends_on:
      - zookeeper

  neo4j:
    image: neo4j:5.14
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt port
    environment:
      # Use the password from your .env plan
      - NEO4J_AUTH=neo4j/password
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
    volumes:
      - 'neo4j_data:/data'

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  neo4j_data:
    driver: local